version: "3.6"
services:
  mongo:
    image: "mongo:4.0.7"
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=docker
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password

  app-back:
    build:
      context: ./server/docker
    image: "laravelapp"
    ports:
      - 8000:80
    volumes:
      - ./server/:/var/www/html

  app-front:
    image: node:alpine3.10
    ports:
      - 3000:3000
    volumes:
      - ./client:/home/node/app
    working_dir: /home/node/app
    command: sh -c "yarn install --no-update-notifier; yarn start --no-update-notifier"
