version: "3.6"
services:
  mongo:
    image: "mongo:4.0.7"
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=docker
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password

  app-back:
    build:
      context: ./server/docker
    image: "laravelapp"
    ports:
      - 8000:80
    volumes:
      - ./server/:/var/www/html
    networks:
      - default

  blackfire:
    image: blackfire/blackfire:2
    ports:
      - 8307:8307
    environment:
      BLACKFIRE_LOG_LEVEL: 4
      BLACKFIRE_SERVER_ID: $BLACKFIRE_SERVER_ID
      BLACKFIRE_SERVER_TOKEN: $BLACKFIRE_SERVER_TOKEN
      BLACKFIRE_CLIENT_ID: $BLACKFIRE_CLIENT_ID
      BLACKFIRE_CLIENT_TOKEN: $BLACKFIRE_CLIENT_TOKEN

  app-front:
    image: node:alpine3.10
    ports:
      - 3000:3000
    volumes:
      - ./client:/home/node/app
    working_dir: /home/node/app
    command: sh -c "yarn install --no-update-notifier; yarn start --no-update-notifier"
    networks:
      - default
    links:
      - app-back

networks:
  default:
    name: front_default
